### ISSUE TITLE
loader - model loading from model sometimes unsuccessful

### ISSUE THREAD

**Issue by raulir** [raulir/bccms#513]
loader - model loading from model sometimes unsuccessful

[22-Sep-2020 09:39:53 UTC] PHP Notice:  Undefined property: user::$cms_page_panel_model in /var/www/html/zzz.com/system/core/Model.php on line 14
[22-Sep-2020 09:39:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function update_cms_page_panel() on null in /var/www/html/zzz.com/modules/cg/models/message_model.php:75
Stack trace:
#0 /var/www/html/zzz.com/modules/cg/panels/usermessages.php(25): message_model->add_message(Array)
#1 /var/www/html/zzz.com/system/core/Controller.php(179): usermessages->panel_action(Array)
#2 /var/www/html/zzz.com/system/core/Controller.php(117): CI_Controller->run_panel_method('cg/usermessages', 'panel_action', Array)
#3 /var/www/html/zzz.com/system/core/Controller.php(629): CI_Controller->run_action('cg/usermessages', Array)
#4 /var/www/html/zzz.com/system/core/controller_ajax_api.php(46): CI_Controller->ajax_panel('cg/usermessages', Array)
#5 /var/www/html/zzz.com/system/core/CodeIgniter.php(222): Ajax_api->get_panel()
#6 /var/www/html/zzz.com/system/cms.php(75): require_once('/var/www/html/c...')
#7 /var/www/html/zzz.com/index.php(17): require_once('/var/www in /var/www/html/zzz.com/modules/cg/models/message_model.php on line 75

code:

	function add_message($params){
		
		if (empty($params['message'])){
			return;
		}
		
		$this->load->model('cms/cms_page_panel_model');
		$this->load->model('user/user_model');
		
		$user = $this->user_model->get_user($params['user_id']);
		
		if (!empty($user)){
			
			if (!empty($user['meta'])){
				$usermeta = json_decode($user['meta'], true);
			} else {
				$usermeta = [];
			}
			
			if(empty($usermeta['messages'])){
				$usermeta['messages'] = [];
			}
			
			// check if post with this id already exists
			foreach($usermeta['messages'] as $message){
				if ($message['type'] == 'post' && $message['message'] == $params['message']){
					return false;
				}
			}
			
			$usermeta['messages'][] = [
					'type' => $params['type'],
					'from' => !empty($params['from']) ? $params['from'] : 0,
					'topic_id' => (!empty($params['topic_id']) && $params['topic_id'] !== 'all') ? $params['topic_id'] : 'other',
					'message' => $params['message'],
					'time' => time(),
			];
		
error ->>>>			$this->cms_page_panel_model->update_cms_page_panel($params['user_id'], ['meta' => json_encode($usermeta, JSON_PRETTY_PRINT)]);
		
		}
		
		return true;
		
	}

**Comment by raulir** [comment]
Reason of bug is that sometimes there is second singleton created, when running class function through wrapper.

Needs deeper analysis, how to resolve this. Possibly together with router work.

**Comment by raulir** [comment]
loader refactored in feature branch
