### ISSUE TITLE
backup - import breaks database with fatal

### ISSUE THREAD

**Issue by raulir** [raulir/bccms#556]
When importing, sometimes, cms_page_panel table gets renamed to _bu and then fatal:

Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in C:\xampp\htdocs\futureworks\system\database\drivers\mysqli\mysqli_result.php:37 Stack trace: #0 C:\xampp\htdocs\futureworks\system\database\drivers\mysqli\mysqli_result.php(37): mysqli_num_rows(true) #1 C:\xampp\htdocs\futureworks\system\database\DB_driver.php(386): CI_DB_mysqli_result->num_rows() #2 C:\xampp\htdocs\futureworks\modules\cms\models\cms_update_model.php(632): CI_DB_driver->query('RENAME TABLE `c...') #3 C:\xampp\htdocs\futureworks\modules\cms\panels\cms_dump.php(267): cms_update_model->run_sql('RENAME TABLE `c...') #4 C:\xampp\htdocs\futureworks\system\core\Controller.php(147): cms_dump->panel_action(Array) #5 C:\xampp\htdocs\futureworks\system\core\Controller.php(90): CI_Controller->run_panel_method('cms/cms_dump', 'panel_action', Array) #6 C:\xampp\htdocs\futureworks\system\core\Controller.php(736): CI_Controller->run_action('cms/cms_dump', Array) #7 C:\xampp\htdocs\futureworks\modules\cms\controllers\admin.php(269): CI_Controller->render(Array) #8 C:\xampp\htdocs\futureworks\system\core\CodeIgniter.php(214): admin->dump() #9 C:\xampp\htdocs\futureworks\system\cms.php(75): require_once('C:\\xampp\\htdocs...') #10 C:\xampp\htdocs\futureworks\index.php(17): require_once('C:\\xampp\\htdocs...') #11 {main} thrown in C:\xampp\htdocs\futureworks\system\database\drivers\mysqli\mysqli_result.php on line 37

Later any request:
Database error: Table 'myproject.cms_page_panel' doesn't exist

**Comment by raulir** [comment]
ok
